unit Emater.Produtividade.Consts;

interface

const
  PRODUTIVIDADE_REPLICACAO_TABELAS_FATER = 'TAB_PRD_FATER|TAB_PRD_FATER_TECNICA|TAB_PRD_FATER_FERRAMENTA|TAB_PRD_FATER_BENEFICIARIO|TAB_PRD_FATER_PARTICIPANTE|TAB_PRD_FATER_FUNCIONARIO|TAB_PRD_FATER_ORGANIZACAO|TAB_PRD_FATER_COMUNIDADE|TAB_PRD_FATER_PRODUTO';
  PRODUTIVIDADE_INFORMACAO_SELECIONAR_PRODUTO = 'Selecione um produto antes de confirmar.';

implementation

end.
